In [16]:
#Задача №6
import numpy as np

p = int(input())
k = int(input())
x = np.random.random(p).reshape(p,1)
y = np.eye(p) #единичная матрица размером рхр
a = y * x
u = np.random.random((p,k))
v = np.random.random((k,p))
c = np.eye(k)



def woodbury(a, u, v):
    a1 = np.linalg.inv(a) #строим обратную матрицу
    f = np.linalg.inv(c + v @ a1 @ u)
    return a1 - a1 @ u @ f @ v @ a1
woodbury(a, u, v)




def realwoodbury(a, u, v):
    return np.linalg.inv(a + u @ v)




realwoodbury(a, u, v)

100
100


array([[ 1.22450879,  0.7462674 ,  0.54662752, ...,  1.22311088,
         0.74818344, -2.03449177],
       [ 0.25453693,  0.06150432, -0.27249768, ...,  0.69402938,
         0.26236414, -0.91715446],
       [-0.83228098, -0.10964981, -0.96423812, ...,  0.7758173 ,
         0.03162478, -0.17374104],
       ...,
       [-0.12026629,  0.25766919, -0.20744153, ..., -0.72253235,
        -0.09154198,  0.99088479],
       [ 0.73862838,  0.11129526,  1.11607073, ..., -0.076602  ,
         0.32461664, -0.63726517],
       [ 0.15609626, -0.13953967,  0.84589031, ..., -0.79956829,
        -0.08469749,  0.57327645]])

In [ ]:
#Задача 3
import numpy as np
import matplotlib
A = np.array([[3,0], [0,-2]])
Lv, Sig, Rv = np.linalg.svd(A)
print(Lv, Rv)

In [2]:
#Задача 2в)
import numpy as np
import matplotlib
A = np.array([[1,1], [1,1]])
At = np.transpose(A)
B = np.matmul(A, At)
C = np.matmul(At, A)
D = np.linalg.eig(B)
#SCH,
U = np.linalg.eig(B)
E = np.linalg.eig(C)
U = D[1]
V = E[1]
SCH = D[0]
Sig = np.array([[SCH[0]**0.5, 0], [0, SCH[1]**0.5]])
print(U)
print(Sig)
print(V)


[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[2.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.10734243e-08]]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [3]:
#Задача 2б)
import numpy as np
import matplotlib
A = np.array([[0,2], [0,0], [0,0], [0,0]])
At = np.transpose(A)
B = np.matmul(A, At)
C = np.matmul(At, A)
D = np.linalg.eig(B)
#SCH,
U = np.linalg.eig(B)
E = np.linalg.eig(C)
U = D[1]
V = E[1]
SCH = D[0]
Sig = np.array([[SCH[0]**0.5, 0, 0, 0], [0, SCH[1]**0.5, 0, 0], [0, 0, SCH[2]**0.5, 0], [0, 0, 0, SCH[3]**0.5]])
print(U)
print(Sig)
print(V)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[2. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0.]
 [0. 1.]]


In [4]:
#Задача 2а)
import numpy as np
import matplotlib
A = np.array([[3,0], [0,-2]])
At = np.transpose(A)
B = np.matmul(A, At)
C = np.matmul(At, A)
D = np.linalg.eig(B)
#SCH,
U = np.linalg.eig(B)
E = np.linalg.eig(C)
U = D[1]
V = E[1]
SCH = D[0]
Sig = np.array([[(SCH[0])**0.5, 0], [0, (SCH[1])**0.5]])
print(U)
print(Sig)
print(V)

[[1. 0.]
 [0. 1.]]
[[3. 0.]
 [0. 2.]]
[[1. 0.]
 [0. 1.]]


In [27]:
def re_m(L, U, P):
    return L @ U @ np.linalg.inv(P)



def diy_LU_v3(a):
    N = a.shape[0]
    U = a.copy()
    P = np.eye(N)
    L = np.eye(N)
    for k in range(0, N - 1):
        max_element = k + np.argmax(abs(U[k:, k]))
        if max_element != k:
            P_temp = np.eye(N)
            P_temp[k,k], P_temp[max_element,max_el] = 0, 0
            P_temp[k,max_element], P_temp[max_element,k] = 1, 1
            P = P_temp @ P
            L = P_temp @ L
            U = P_temp @ U
            lam = np.eye(N)
            gamma = U[k+1:, k] / U[k, k]
            lam[k+1:, k] = -gamma
            U = lam @ U
            L = lam @ L
            L = np.linalg.inv(L @ np.linalg.inv(P))
            return P, L, U
        np.set_printoptions(precision=3)
        P, L, U = diy_LU_v3(a1)
        print (P, "\n"*2, L, "\n"*2, U, "\n")
        print(L @ U - P @ a1, "\n")
        print (restore_matrix(L, U, P), "\n")
        print (a1)
        
        
        
        

        print (P, "\n"*2, L, "\n"*2, U, "\n")
        print(L @ U - P @ a, "\n")
        print (restore_m(L, U, P), "\n")
print (a)


[[0.69896962 0.         0.         ... 0.         0.         0.        ]
 [0.         0.72666686 0.         ... 0.         0.         0.        ]
 [0.         0.         0.12139078 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.3025297  0.         0.        ]
 [0.         0.         0.         ... 0.         0.91446233 0.        ]
 [0.         0.         0.         ... 0.         0.         0.64694378]]


In [39]:
#Задача 5, первый вариант
def woodbury_einsum(A, U, V, k):
    A_inv = np.diag(1./np.diag(A))
    tmp   = np.einsum('ab,bc,cd->ad',
                      V, A_inv, U,
                      optimize=['einsum_path', (1, 2), (0, 1)])
    B_inv = np.linalg.inv(np.eye(k) + tmp)
    tmp   = np.einsum('ab,bc,cd,de,ef->af',
                      A_inv, U, B_inv, V, A_inv,
                      optimize=['einsum_path', (0, 1), (0, 1), (0, 2), (0, 1)])
    return A_inv - tmp
print(woodbury_einsum(A, U, V, k))

[[-2.35052831  0.00583502  0.07011154 ... -0.04685968  0.05746135
   0.19112226]
 [ 0.00583502  0.92307824 -0.24019295 ...  0.22184628 -0.04859622
  -0.13804588]
 [ 0.07011154 -0.24019295  0.49952314 ...  0.83482591 -0.1936324
   0.11816764]
 ...
 [-0.04685968  0.22184628  0.83482591 ...  0.25716923  0.19339463
  -0.22640378]
 [ 0.05746135 -0.04859622 -0.1936324  ...  0.19339463  0.48594789
   0.03791837]
 [ 0.19112226 -0.13804588  0.11816764 ... -0.22640378  0.03791837
  -4.47582325]]


In [37]:
#Вариант номер 2
def woodbury(A, U, V, k):
    A_inv = np.diag(1./np.diag(A))  # Fast matrix inversion of a diagonal.
    B_inv = np.linalg.inv(np.eye(k) + V @ A_inv @ U)
    return A_inv - (A_inv @ U @ B_inv @ V @ A_inv)
n = 100000
p = 1000
k = 100
A = np.diag(np.random.randn(p))
U = np.random.randn(p, k)
V = U.T
M = U @ V + A
M_inv = woodbury(A, U, V, k)
assert np.allclose(M @ M_inv, np.eye(p))
print(woodbury(A, U, V, k))


[[ 6.09836199e-01 -5.96512546e-03  1.28851077e-01 ...  3.78928892e-02
  -1.75624997e-01 -3.84817962e-01]
 [-5.96512546e-03  3.50436611e+01  3.47220539e-01 ... -2.24513746e-02
   4.91687180e+00  3.95479625e+00]
 [ 1.28851077e-01  3.47220539e-01 -5.43531813e-01 ...  3.62740235e-01
  -1.44507153e+00 -3.03482081e+00]
 ...
 [ 3.78928892e-02 -2.24513746e-02  3.62740235e-01 ...  7.65887319e-01
  -3.29868924e-01 -6.32416895e-01]
 [-1.75624997e-01  4.91687180e+00 -1.44507153e+00 ... -3.29868924e-01
  -3.23071041e-01  2.67400486e+00]
 [-3.84817962e-01  3.95479625e+00 -3.03482081e+00 ... -6.32416895e-01
   2.67400486e+00  6.98421584e+00]]
