In [1]:
#Задача №6
import numpy as np

p = int(input())
k = int(input())
x = np.random.random(p).reshape(p,1)
y = np.eye(p) #единичная матрица размером рхр
a = y * x
u = np.random.random((p,k))
v = np.random.random((k,p))
c = np.eye(k)



def woodbury(a, u, v):
    a1 = np.linalg.inv(a) #строим обратную матрицу
    f = np.linalg.inv(c + v @ a1 @ u)
    return a1 - a1 @ u @ f @ v @ a1
woodbury(a, u, v)
def realwoodbury(a, u, v):
    return np.linalg.inv(a + u @ v)




realwoodbury(a, u, v)

10
3


array([[ 2.00304899e+00,  5.33602285e-01, -1.28155939e-01,
        -6.80939486e-02,  2.23965099e-01, -2.87684407e+00,
         1.08757997e+00,  1.05760303e+00,  5.20478983e-01,
        -8.86560166e-01],
       [-2.30420833e-01,  3.97331069e+00, -3.08421826e-01,
        -2.02719736e-01,  8.53469416e-01, -7.88054522e+00,
         3.07659434e+00,  3.63992135e+00,  1.26869196e+00,
        -2.03844242e+00],
       [-7.44006525e-01,  1.11992745e+00,  2.06316146e+00,
        -7.23632374e-02, -3.36750198e-01, -1.03061572e+00,
         1.69048616e+00, -3.78851775e-01,  1.44583201e+00,
        -2.84268891e+00],
       [ 1.40916457e-01, -3.65761910e-01,  9.73426137e-02,
         3.18781932e+00, -7.41531627e-02, -6.35430465e-01,
        -6.86487029e-01, -4.66938416e-01, -3.92295897e-01,
         7.04576854e-01],
       [-3.08107164e+00,  1.28225709e+01, -3.00982621e+00,
        -1.67404940e+00,  1.11281328e+01, -5.11419225e+01,
         2.65339279e+01,  2.71755430e+01,  1.22720950e+01,
        -2.

In [ ]:
#Задача 3
import numpy as np
import matplotlib
A = np.array([[3,0], [0,-2]])
Lv, Sig, Rv = np.linalg.svd(A)
print(Lv, Rv)

In [2]:
#Задача 2в)
import numpy as np
import matplotlib
A = np.array([[1,1], [1,1]])
At = np.transpose(A)
B = np.matmul(A, At)
C = np.matmul(At, A)
D = np.linalg.eig(B)
#SCH,
U = np.linalg.eig(B)
E = np.linalg.eig(C)
U = D[1]
V = E[1]
SCH = D[0]
Sig = np.array([[SCH[0]**0.5, 0], [0, SCH[1]**0.5]])
print(U)
print(Sig)
print(V)


[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[2.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.10734243e-08]]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [3]:
#Задача 2б)
import numpy as np
import matplotlib
A = np.array([[0,2], [0,0], [0,0], [0,0]])
At = np.transpose(A)
B = np.matmul(A, At)
C = np.matmul(At, A)
D = np.linalg.eig(B)
#SCH,
U = np.linalg.eig(B)
E = np.linalg.eig(C)
U = D[1]
V = E[1]
SCH = D[0]
Sig = np.array([[SCH[0]**0.5, 0, 0, 0], [0, SCH[1]**0.5, 0, 0], [0, 0, SCH[2]**0.5, 0], [0, 0, 0, SCH[3]**0.5]])
print(U)
print(Sig)
print(V)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[2. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0.]
 [0. 1.]]


In [4]:
#Задача 2а)
import numpy as np
import matplotlib
A = np.array([[3,0], [0,-2]])
At = np.transpose(A)
B = np.matmul(A, At)
C = np.matmul(At, A)
D = np.linalg.eig(B)
#SCH,
U = np.linalg.eig(B)
E = np.linalg.eig(C)
U = D[1]
V = E[1]
SCH = D[0]
Sig = np.array([[(SCH[0])**0.5, 0], [0, (SCH[1])**0.5]])
print(U)
print(Sig)
print(V)

[[1. 0.]
 [0. 1.]]
[[3. 0.]
 [0. 2.]]
[[1. 0.]
 [0. 1.]]
